BRIDGE_NET="172.25.0."

servers = [
  {
    :hostname => "my-vm2",
    :name => "my_vm2",
    :ip => BRIDGE_NET + "112",
    :ip_int => "1",
    :ram => 1024
  },
  {
    :hostname => "my-vm3",
    :name => "my_vm3",
    :ip => BRIDGE_NET + "113",
    :ip_int => "2",
    :ram => 1024
  }
]

Vagrant.configure("2") do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostname = machine[:hostname]
    node.vm.network "public_network",
        ip: machine[:ip],
        bridge: 'Realtek PCIe GbE Family Controller'
    node.vm.provider "virtualbox" do |vb|
        vb.name = machine[:name]
        vb.memory = machine[:ram]
        end
    end
  end
end