Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.network "public_network", use_dhcp_assigned_default_route: true
    config.vm.provider "virtualbox" do |v|
    v.name = "my_vm"
    v.memory = 1024
    v.cpus = 2
    end
end