Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.network "public_network",
	    bridge: "Realtek PCIe GbE Family Controller",
	    ip: "172.25.0.111"
	config.vm.provision "shell",
        run: "always",
        inline: "route add default gw 172.25.0.1"
    config.vm.provider "virtualbox" do |v|
    v.name = "my_vm"
    v.memory = 1024
    v.cpus = 2
    end
end